#pragma once

#define MAX_WAIT_TIME_MS    (10000)

/**
 * Bootloader version
 */
#define BOOTLOADER_MAJOR_VERSION (0)
#define BOOTLOADER_MINOR_VERSION (0)
#define BOOTLOADER_PATCH_VERSION (0)
#define MAX_WAIT_TIME_MS (10000)

/**
 * Memory map
 */
#define BOOTLOADER_START (0x08000000)
#define BOOTLOADER_SIZE  (10 * 1024) // 10Kb

#define FLASH_SIZE ((*(volatile uint16_t *) 0x1FFFF7E0) * 1024)

#define FIRMWARE_BANK_SIZE   ((FLASH_SIZE - BOOTLOADER_SIZE) / 2)
#define FIRMWARE_BANK1_START (BOOTLOADER_START + BOOTLOADER_SIZE)
#define FIRMWARE_BANK2_START (FIRMWARE_BANK1_START + FIRMWARE_BANK_SIZE)
